
server:
    port: 8080 #启动端口

spring:
    application:
        name: pm-person-manager
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        database: mysql
    datasource:
        hikari:
            driver-class-name: com.mysql.cj.jdbc.Driver
            username: root
            password: Nlelpct@1234
            jdbc-url: jdbc:mysql://${MYSQL_HOST:192.168.10.14}:${MYSQL_PORT:3306}/wl_user_co_manager?useUnicode=true&characterEncoding=UTF8

#配置日志
logging:
    pattern:
        console: "[%d{yyyy-MM-dd HH:mm}]-%-5p:%m%n"
        file: "[%d{yyyy-MM-dd HH:mm}]-%-5p:%m%n"
    level:
        root: info
    file: log/xxx.log














