spring:
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
            instanceName: DefaultQuartzScheduler
            rmi:
              export: false
              proxy: false
            wrapJobExecutionInUserTransaction: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 15
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          jobStore:
            misfireThreshold: 5000
            isClustered: true
            clusterCheckinInterval: 2000
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            dataSource: qzDS
          dataSource:
            qzDS:
              driver: com.mysql.cj.jdbc.Driver
              URL: jdbc:mysql://192.168.10.14:3307/test?useUnicode=true&characterEncoding=UTF8
              user: root
              password: 123456
              maxConnections: 10
  # 配置JPA
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: mysql
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456    #Nlelpct@1234
      jdbc-url: jdbc:mysql://192.168.10.14:3307/test?useUnicode=true&characterEncoding=UTF8
#配置日志
#logging:
#  pattern:
#    console: "[%d{yyyy-MM-dd HH:mm}]-%-5p:%m%n"
#    file: "[%d{yyyy-MM-dd HH:mm}]-%-5p:%m%n"
#  level:
#    root: info
#  file: log/xxx.log
