spring:
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
            instanceName: DefaultQuartzScheduler
            rmi:
              export: false
              proxy: false
            wrapJobExecutionInUserTransaction: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 15
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          jobStore:
            misfireThreshold: 5000
            isClustered: true
            clusterCheckinInterval: 2000
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            dataSource: qzDS
          dataSource:
            qzDS:
              driver: com.mysql.cj.jdbc.Driver
              URL: jdbc:mysql://192.168.10.14:3307/k8s?characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
              user: root
              password: 123456
              maxConnections: 10